### ISSUE TITLE
Error running frontend

### ISSUE THREAD

**Issue by zarbielli** [falko-org/Falko#342]
I just cloned the project and try run it but I got the following error:

ERROR: Network falko20172backend_default declared as external, but could not be found. Please create the network manually using `docker network create falko20172backend_default` and try again.

The backend server is running normally

**Comment by alaxalves** [comment]
This is because we recently had altered the variables of API's docker-compose file, changing your `docker-compose.yml` to:
``` yml
version: '2'
services:
  
  front:
    container_name: falko-front
    image: alaxalves/front:1.5
    command: ["./scripts/sh/start-dev.sh"]
    volumes:
      - .:/Falko-2017.2-FrontEnd
    external_links:
      - falko-backend
    ports:
      - 8080:8080
    networks:
      - default
      - falko-backend
    ipc: host

networks:
  falko-backend:
    external: true
```
should do the trick.
